### ISSUE TITLE
Compare artboard element with artboard background color

### ISSUE THREAD

**Issue by eonvdk** [ygev/cluse#3]
Sometimes the background of the artboard itself has a color set to it.
It would be great to be able to compare a single element from the page with the color of the artboard background.

REPRO STEPS
- Create a new artboard.
- Assign a color to it. (With the artboard selected, change its color on the right side panel under Artboards > Background color)
- Create any element on the artboard.
- Select that element then select the artboard too.

VIDEO of the REPRO [https://www.dropbox.com/s/htrcxx0fgxj39ld/cluse%20and%20background.mov?dl=0](url)

EXPECTED
- When running the plugin, it would behave as when two elements from the artboard are selected and show the results.

ACTUAL
- Nothing happens.

**Comment by ygev** [comment]
This is solved in Cluse 1.1.0. You can download it [here](https://github.com/ygev/cluse/releases/download/v1.1.0/Cluse.sketchplugin.zip) if it didn't automatically update in Sketch!
