### ISSUE TITLE
Doesn't work with Sketch 51

### ISSUE THREAD

**Issue by idulnyavka** [ygev/cluse#5]
The plugin must be great and useful for quick tunes, but after I installed plugin for Sketch 51.3 (57544) nothing happens when I run plugin.
Is prev versions support dropped and it's working only on latest version of Sketch? Could someone check this?

**Comment by ygev** [comment]
Sorry, previous version support has not yet been implemented but it is in the works for a future update. I am marking this as an enhancement.

**Comment by idulnyavka** [comment]
Thank you!
